version: '3'

services:

  monolith:
    image: csantosm/mca_monolith
    restart: on-failure
    network_mode: host
    ports:
      - 8080:8080
    expose:
      - '8080'


  order-microservice:
    image: csantosm/mca_order_microservice
    restart: on-failure
    network_mode: host
    depends_on:
      - monolith
    ports:
      - 8081:8081
    expose:
      - '8081'


  nginx:
    build: ./nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
        - monolith
        - order-microservice
    links:
        - monolith
        - order-microservice
